import fs from 'fs';
import path from 'path';

/**
 * Usage:
 * node scripts/obfuscate_icons.js [--compress] [--width <n>] [--height <n>]
 * 
 * 使用说明:
 * node scripts/obfuscate_icons.js [--compress] [--width <n>] [--height <n>]
 *
 * Options:
 *   -c, --compress  Enable image compression (using sharp) / 开启压缩
 *   -w, --width     Set max width for the image / 设置最大宽度
 *   -h, --height    Set max height for the image / 设置最大高度
 *
 * Example:
 *   node scripts/obfuscate_icons.js --compress --width 400
 */

// Parse arguments
const args = process.argv.slice(2);
const options = {
    compress: args.includes('--compress') || args.includes('-c'),
    width: parseInt(args[args.indexOf('--width') + 1] || args[args.indexOf('-w') + 1]) || null,
    height: parseInt(args[args.indexOf('--height') + 1] || args[args.indexOf('-h') + 1]) || null,
};

let sharp;
if (options.compress || options.width || options.height) {
    try {
        sharp = (await import('sharp')).default;
    } catch (e) {
        console.error('Error: "sharp" library is required for compression/resizing. Please run "pnpm install sharp".');
        process.exit(1);
    }
}

/**
 * Obfuscates a file by converting it to base64 and reversing the string.
 * This helps bypass simple regex-based scanners that look for crypto addresses.
 */
async function obfuscate(filePath, opts) {
    if (!fs.existsSync(filePath)) {
        console.error(`File not found: ${filePath}`);
        return null;
    }

    let buffer = fs.readFileSync(filePath);
    const originalSize = buffer.length;

    if (sharp && (opts.compress || opts.width || opts.height)) {
        let pipeline = sharp(buffer);
        
        if (opts.width || opts.height) {
            pipeline = pipeline.resize({
                width: opts.width,
                height: opts.height,
                fit: 'inside',
                withoutEnlargement: true
            });
        }

        if (opts.compress) {
            pipeline = pipeline.png({ palette: true, quality: 80 });
        }

        buffer = await pipeline.toBuffer();
        console.log(`Compressed ${path.basename(filePath)}: ${(originalSize / 1024).toFixed(1)}KB -> ${(buffer.length / 1024).toFixed(1)}KB`);
    }

    const base64 = buffer.toString('base64');
    return base64.split('').reverse().join('');
}

function chunkString(str, size) {
    const numChunks = Math.ceil(str.length / size);
    const chunks = new Array(numChunks);
    for (let i = 0, o = 0; i < numChunks; ++i, o += size) {
        chunks[i] = str.substr(o, size);
    }
    return chunks;
}

const kofiPath = 'scripts/kofi.png';
const wxPath = 'scripts/wxds.png';

async function run() {
    const kofiObf = await obfuscate(kofiPath, options);
    const wxObf = await obfuscate(wxPath, options);

    if (kofiObf && wxObf) {
        const output = `
// This file is auto-generated by scripts/obfuscate_icons.js
// DO NOT EDIT MANUALLY

const decodeImage = (chunks: string[]): string => {
  const reversed = chunks.join("");
  return "data:image/png;base64," + reversed.split("").reverse().join("");
};

const KofiChunks: string[] = ${JSON.stringify(chunkString(kofiObf, 100), null, 2)};

const WXChunks: string[] = ${JSON.stringify(chunkString(wxObf, 100), null, 2)};

export const KofiImage = decodeImage(KofiChunks);
export const WXImage = decodeImage(WXChunks);
`;

        fs.writeFileSync('src/lib/icons.ts', output.trim() + '\n');
        console.log('Successfully updated src/lib/icons.ts');
    }
}

run().catch(console.error);
