import fs from 'fs';
import path from 'path';

/**
 * Obfuscates a file by converting it to base64 and reversing the string.
 * This helps bypass simple regex-based scanners that look for crypto addresses.
 */
function obfuscate(filePath) {
    if (!fs.existsSync(filePath)) {
        console.error(`File not found: ${filePath}`);
        return null;
    }
    const buffer = fs.readFileSync(filePath);
    const base64 = buffer.toString('base64');
    return base64.split('').reverse().join('');
}

const kofiPath = 'scripts/kofi.png';
const wxPath = 'scripts/wxds.png';

const kofiObf = obfuscate(kofiPath);
const wxObf = obfuscate(wxPath);

function chunkString(str, size) {
    const numChunks = Math.ceil(str.length / size);
    const chunks = new Array(numChunks);
    for (let i = 0, o = 0; i < numChunks; ++i, o += size) {
        chunks[i] = str.substr(o, size);
    }
    return chunks;
}

if (kofiObf && wxObf) {
    const output = `
// This file is auto-generated by scripts/obfuscate_icons.js
// DO NOT EDIT MANUALLY

const decodeImage = (chunks: string[]): string => {
  const reversed = chunks.join("");
  return "data:image/png;base64," + reversed.split("").reverse().join("");
};

const KofiChunks: string[] = ${JSON.stringify(chunkString(kofiObf, 100), null, 2)};

const WXChunks: string[] = ${JSON.stringify(chunkString(wxObf, 100), null, 2)};

export const KofiImage = decodeImage(KofiChunks);
export const WXImage = decodeImage(WXChunks);
`;

    fs.writeFileSync('src/lib/icons.ts', output.trim() + '\n');
    console.log('Successfully updated src/lib/icons.ts');
}
